version: '3.7'

services:
  db:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: shortener
  shortener:
    build:
      context: .
    image: shortener
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080