spring:
  java:
    properties:
      hiibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: shortener
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://db:5432/shortener
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
application-host: http://localhost